name: Deploy to EC2

on:
  push:
    branches:
      - main   # 👈 runs when you push to main (change if you use another branch)

jobs:
  deploy:
    runs-on: self-hosted   # 👈 this tells GitHub to use your EC2 runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # 👈 change if your project needs a different version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Restart PM2 process
        run: |
          # Stop the old app if running
          pm2 stop eagles-backend || true
          # Start the new build (adjust entry file if needed)
          pm2 start dist/server.js --name eagles-backend
          # Save PM2 process list so it persists across reboots
          pm2 save
